# Generated by Django 2.2.3 on 2019-07-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_mater_per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'doc_mater_per',
            },
        ),
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id_docentes', models.BigAutoField(db_column='id_docente', primary_key=True, serialize=False)),
                ('especializacion', models.CharField(choices=[('Normalista', 'Normalista'), ('licenciado', 'licenciado'), ('especializacion', 'especializacion'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('otros', 'otros')], db_column='especializacion', max_length=100)),
                ('grado_carrera', models.CharField(db_column='grado_carrera', max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id_estudiante', models.BigAutoField(db_column='id_estudiante', primary_key=True, serialize=False)),
                ('grado_esc', models.IntegerField(db_column='grado_esc', max_length=3)),
            ],
            options={
                'managed': False,
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('id_grado', models.BigAutoField(db_column='id_grado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=10)),
                ('jornada', models.CharField(db_column='jornada', max_length=10)),
                ('salon', models.CharField(db_column='salon', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'grado',
            },
        ),
        migrations.CreateModel(
            name='grado_estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField(db_column='fec_ini')),
                ('fec_fin', models.DateField(db_column='fec_fin')),
            ],
            options={
                'managed': False,
                'db_table': 'grado_estudiantes',
            },
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id_materia', models.BigAutoField(db_column='id_materia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('duracion', models.IntegerField(db_column='duracion', default=0, max_length=3)),
            ],
            options={
                'managed': False,
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='materia_periodo',
            fields=[
                ('id_registro', models.BigAutoField(db_column='id_registro', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'materia_periodo',
            },
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'managed': False,
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id_periodo', models.BigIntegerField(db_column='id_periodo', primary_key=True, serialize=False)),
                ('fecha_incio', models.DateField(db_column='fecha_incio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
            ],
            options={
                'managed': False,
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id_personas', models.BigIntegerField(db_column='id_personas', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='nombre')),
                ('apellido', models.TextField(db_column='apellido')),
                ('direccion', models.TextField(db_column='direccion')),
                ('telefono', models.CharField(db_column='telefono', max_length=10)),
                ('fecha_nac', models.DateField(db_column='fecha_nac', max_length=10)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjeta identidad'), ('OT', 'Otros')], db_column='tipo_doc', max_length=7)),
            ],
            options={
                'managed': False,
                'db_table': 'personas',
            },
        ),
    ]
