# Generated by Django 2.2.3 on 2019-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.TextField(db_column='tabla')),
                ('usuario', models.TextField(db_column='usuario')),
                ('fecha', models.DateTimeField(db_column='fecha')),
                ('operacion', models.TextField(db_column='operacion')),
                ('valor_inicial', models.TextField(db_column='valor_inicial')),
                ('valor_final', models.TextField(db_column='valor_final')),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='doc_mater_per',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doc_mater_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id_docentes', models.BigAutoField(db_column='id_docente', primary_key=True, serialize=False)),
                ('especializacion', models.CharField(choices=[('Normalista', 'Normalista'), ('licenciado', 'licenciado'), ('especializacion', 'especializacion'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('otros', 'otros')], db_column='especializacion', max_length=100)),
                ('grado_carrera', models.CharField(db_column='grado_carrera', max_length=100)),
            ],
            options={
                'db_table': 'docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id_estudiante', models.BigAutoField(db_column='id_estudiante', primary_key=True, serialize=False)),
                ('grado_esc', models.IntegerField(db_column='grado_esc')),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('id_grado', models.BigAutoField(db_column='id_grado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=10)),
                ('jornada', models.CharField(db_column='jornada', max_length=10)),
                ('salon', models.CharField(db_column='salon', max_length=10)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='grado_estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ini', models.DateField(db_column='fec_ini')),
                ('fec_fin', models.DateField(db_column='fec_fin')),
            ],
            options={
                'db_table': 'grado_estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id_materia', models.BigAutoField(db_column='id_materia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('duracion', models.IntegerField(db_column='duracion', default=0)),
            ],
            options={
                'db_table': 'materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='materia_periodo',
            fields=[
                ('id_registro', models.BigAutoField(db_column='id_registro', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'materia_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notas', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'db_table': 'notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id_periodo', models.BigIntegerField(db_column='id_periodo', primary_key=True, serialize=False)),
                ('fecha_incio', models.DateField(db_column='fecha_incio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id_personas', models.BigIntegerField(db_column='id_personas', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='nombre')),
                ('apellido', models.TextField(db_column='apellido')),
                ('direccion', models.TextField(db_column='direccion')),
                ('telefono', models.CharField(db_column='telefono', max_length=10)),
                ('fecha_nac', models.DateField(db_column='fecha_nac', max_length=10)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cedula'), ('TI', 'Tarjeta identidad'), ('OT', 'Otros')], db_column='tipo_doc', max_length=7)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
    ]
